name: finance-test
channels:
 - defaults
dependencies:
 - arrow==1.2.3
 - beautifulsoup4==4.12.2
 - blinker==1.6.2
 - certifi==2023.7.22
 - dill==0.3.7
 - idna==3.4
 - Jinja2==3.1.2
 - mccabe==0.7.0
 - packaging==23.1
 - platformdirs==3.10.0
 - pydocstyle==6.3.0
 - python-dateutil==2.8.2
 - requests==2.31.0
 - six==1.16.0
 - snowballstemmer==2.2.0
 - soupsieve==2.5
 - pip:
    - charset-normalizer==3.2.0
    - werkzeug==2.3.7
    - astroid==2.15.6
    - wrapt==1.15.0
    - tomlkit==0.12.1
    - pyyaml==6.0.1
    - lazy-object-proxy==1.9.0
    - itsdangerous==2.1.2
    - pluggy==1.3.0
    - flask==2.3.3
    - pycodestyle==2.11.0
    - urllib3==2.0.4
    - isort==5.12.0
    - html5validator==0.4.2
    - click==8.1.7
    - markupsafe==2.1.3
    - pytest-mock==3.11.1
    - iniconfig==2.0.0
    - pylint==2.17.5
    - bs4==0.0.1
    - pytest==7.4.2
